# Generated by Django 5.1.3 on 2024-11-12 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0002_devicehistory_devices_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicehistory',
            name='description',
            field=models.CharField(default='None', max_length=100),
        ),
    ]
