# Generated by Django 5.1.3 on 2024-11-12 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0003_devicehistory_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devices',
            name='history',
            field=models.ManyToManyField(to='communication.devicehistory'),
        ),
        migrations.AlterField(
            model_name='user',
            name='devices',
            field=models.ManyToManyField(to='communication.devices'),
        ),
    ]
