# Generated by Django 5.1.3 on 2024-11-22 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0004_alter_devices_history_alter_user_devices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homeassistant',
            name='token',
            field=models.CharField(max_length=500),
        ),
    ]
