// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCAUB8XMCY4lEhHbuFEX2rddmk1_Lg2IEo',
    appId: '1:782228114211:web:b2bff86b72617fcc4f9a96',
    messagingSenderId: '782228114211',
    projectId: 'controlleriot-2d182',
    authDomain: 'controlleriot-2d182.firebaseapp.com',
    storageBucket: 'controlleriot-2d182.firebasestorage.app',
    measurementId: 'G-XC1817LPY9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDucxC_u9noHlwG_nj4y_RLtGB_M7iAaz0',
    appId: '1:782228114211:android:73d5e65dc0f431284f9a96',
    messagingSenderId: '782228114211',
    projectId: 'controlleriot-2d182',
    storageBucket: 'controlleriot-2d182.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCUwCHXw9VmW-YY4m2vSkAl57CcpmYVl2w',
    appId: '1:782228114211:ios:a679b0990936c04f4f9a96',
    messagingSenderId: '782228114211',
    projectId: 'controlleriot-2d182',
    storageBucket: 'controlleriot-2d182.firebasestorage.app',
    iosBundleId: 'com.example.frontDev',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCUwCHXw9VmW-YY4m2vSkAl57CcpmYVl2w',
    appId: '1:782228114211:ios:a679b0990936c04f4f9a96',
    messagingSenderId: '782228114211',
    projectId: 'controlleriot-2d182',
    storageBucket: 'controlleriot-2d182.firebasestorage.app',
    iosBundleId: 'com.example.frontDev',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCAUB8XMCY4lEhHbuFEX2rddmk1_Lg2IEo',
    appId: '1:782228114211:web:5b556be53fdf1c054f9a96',
    messagingSenderId: '782228114211',
    projectId: 'controlleriot-2d182',
    authDomain: 'controlleriot-2d182.firebaseapp.com',
    storageBucket: 'controlleriot-2d182.firebasestorage.app',
    measurementId: 'G-V9SQFHPM8M',
  );
}
